package com.laboras.pirmas.mybatis.model;

public class Diagnosis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DIAGNOSIS.ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DIAGNOSIS.DESCRIPTION
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DIAGNOSIS.NAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DIAGNOSIS.ID
     *
     * @return the value of PUBLIC.DIAGNOSIS.ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DIAGNOSIS.ID
     *
     * @param id the value for PUBLIC.DIAGNOSIS.ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DIAGNOSIS.DESCRIPTION
     *
     * @return the value of PUBLIC.DIAGNOSIS.DESCRIPTION
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DIAGNOSIS.DESCRIPTION
     *
     * @param description the value for PUBLIC.DIAGNOSIS.DESCRIPTION
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DIAGNOSIS.NAME
     *
     * @return the value of PUBLIC.DIAGNOSIS.NAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DIAGNOSIS.NAME
     *
     * @param name the value for PUBLIC.DIAGNOSIS.NAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}