package com.laboras.pirmas.mybatis.model;

public class PatientDiagnosis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT_DIAGNOSIS.PATIENTS_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private Integer patientsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT_DIAGNOSIS.DIAGNOSES_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private Integer diagnosesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT_DIAGNOSIS.PATIENTS_ID
     *
     * @return the value of PUBLIC.PATIENT_DIAGNOSIS.PATIENTS_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public Integer getPatientsId() {
        return patientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT_DIAGNOSIS.PATIENTS_ID
     *
     * @param patientsId the value for PUBLIC.PATIENT_DIAGNOSIS.PATIENTS_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setPatientsId(Integer patientsId) {
        this.patientsId = patientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT_DIAGNOSIS.DIAGNOSES_ID
     *
     * @return the value of PUBLIC.PATIENT_DIAGNOSIS.DIAGNOSES_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public Integer getDiagnosesId() {
        return diagnosesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT_DIAGNOSIS.DIAGNOSES_ID
     *
     * @param diagnosesId the value for PUBLIC.PATIENT_DIAGNOSIS.DIAGNOSES_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setDiagnosesId(Integer diagnosesId) {
        this.diagnosesId = diagnosesId;
    }
}