package com.laboras.pirmas.mybatis.model;

import lombok.Getter;
import lombok.Setter;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.ADDRESS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.AGE
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.EMAIL
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.GENDER
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.SURNAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.DOCTOR_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    private Integer doctorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.ID
     *
     * @return the value of PUBLIC.PATIENT.ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.ID
     *
     * @param id the value for PUBLIC.PATIENT.ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.ADDRESS
     *
     * @return the value of PUBLIC.PATIENT.ADDRESS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.ADDRESS
     *
     * @param address the value for PUBLIC.PATIENT.ADDRESS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.AGE
     *
     * @return the value of PUBLIC.PATIENT.AGE
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.AGE
     *
     * @param age the value for PUBLIC.PATIENT.AGE
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.EMAIL
     *
     * @return the value of PUBLIC.PATIENT.EMAIL
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.EMAIL
     *
     * @param email the value for PUBLIC.PATIENT.EMAIL
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.GENDER
     *
     * @return the value of PUBLIC.PATIENT.GENDER
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.GENDER
     *
     * @param gender the value for PUBLIC.PATIENT.GENDER
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.NAME
     *
     * @return the value of PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.NAME
     *
     * @param name the value for PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @return the value of PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @param phoneNumber the value for PUBLIC.PATIENT.PHONE_NUMBER
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.SURNAME
     *
     * @return the value of PUBLIC.PATIENT.SURNAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.SURNAME
     *
     * @param surname the value for PUBLIC.PATIENT.SURNAME
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.DOCTOR_ID
     *
     * @return the value of PUBLIC.PATIENT.DOCTOR_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.DOCTOR_ID
     *
     * @param doctorId the value for PUBLIC.PATIENT.DOCTOR_ID
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    @Getter @Setter
    private Doctor doctor;
}