package com.laboras.pirmas.mybatis.dao;

import com.laboras.pirmas.mybatis.model.Diagnosis;
import com.laboras.pirmas.mybatis.model.Patient;
import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DiagnosisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int insert(Diagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    Diagnosis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    List<Diagnosis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int updateByPrimaryKey(Diagnosis record);

    List<Patient> selectPatientsOfDiagnosis(Integer id);
}