package com.laboras.pirmas.mybatis.dao;

import com.laboras.pirmas.mybatis.model.Doctor;

import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    Doctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    List<Doctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int updateByPrimaryKey(Doctor record);
}