package com.laboras.pirmas.mybatis.dao;

import com.laboras.pirmas.mybatis.model.PatientDiagnosis;

import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PatientDiagnosisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT_DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    int insert(PatientDiagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT_DIAGNOSIS
     *
     * @mbg.generated Tue Apr 25 15:56:50 EEST 2023
     */
    List<PatientDiagnosis> selectAll();
}